export enum SendType {
  INSTRUCTION = 'INSTRUCTION', MESSAGING= 'MESSAGING', MESSAGING_TLS = 'MESSAGING_TLS', MESSAGING_MEDICAL = 'MESSAGING_MEDICAL', MESSAGING_PATIENT = 'MESSAGING_PATIENT', SEND_POSTAL = 'SEND_POSTAL'
};
